### ISSUE TITLE
MacOs build - `demo.sh` tries to access private Docker repo

### ISSUE THREAD

**Issue by chbndrhnns** [qwaneu/distributed-ensemble#2]
Running `./demo.sh` fails like this:

```
 => ERROR [internal] load metadata for docker.io/qwan/desktop:latest                                                1.6s
------
 > [internal] load metadata for docker.io/qwan/desktop:latest:
------
Dockerfile:1
--------------------
   1 | >>> FROM qwan/desktop as java
   2 |
   3 |     RUN apt-get -qq update && \
--------------------
ERROR: failed to solve: qwan/desktop: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
sending incremental file list
```

**Comment by mostalive** [comment]
Thanks, looks like I made a porting mistake.

**Comment by mostalive** [comment]
Reproduced. For some reason `qwan/desktop` gets built (in the directory desktop-base), but the `java-intellij` build can't load the image.

``` 
$ docker images
REPOSITORY                                  TAG                     IMAGE ID       CREATED         SIZE
qwan/desktop                                latest                  5dfa143d9ff5   3 minutes ago   609MB
```

**Comment by mostalive** [comment]
@chbndrhnns I've added 'export BUILDKIT=0' to `demo.sh` . Does this work for you? This seemed to work on a 'clean' Mac that didn't have any of the images yet. Not entirely clear why this is needed. https://stackoverflow.com/questions/64221861/an-error-failed-to-solve-with-frontend-dockerfile-v0 

(scripts that use compose files may also need yet another env variable).

**Comment by mostalive** [comment]
I've kept the issue open, @rwestgeest is also looking into it - disabling buildkit is a pretty big workaround. And not necessary on linux.

**Comment by chbndrhnns** [comment]
Using the `demo.sh` script with disabled buildkit worked fine for me now.

**Comment by chbndrhnns** [comment]
However, the UI seems really slow on my M1 macbook. I might need to play with the platform settings and try to build M1 native container images. Do you have an idea how to approach this?

**Comment by mostalive** [comment]
I'm glad it is working for you @chbndrhnns. (on my M1 I got it running, but intellij complained about not being able to run a script, possibly because the volume was mounted incorrectly). @rwestgeest was also wondering about this, as we were discussing whether to add a flag to the build script.

1. Try adding `--platform linux/arm64` to the `build.sh` for `desktop-base`. My guess is it will fail, and that `theasp/novnc` only has an intel build. 
2. Build `theasp/novnc` from source (we have done this in our private stack, but. I forgot why we did this). First step would be to clone that repository and build it using the `--platform` option to be sure. I don't think it is necessary - would be interesting to see if Docker complains about not having specified the platform. I haven't tried this yet.
3. Combine `theasp/novnc` source with the `desktop-base`, `intellij-java` and the demo dockerfile into a multi-stage build, https://stackoverflow.com/questions/33322103/multiple-froms-what-it-means/ , so that having buildkit or not doesn't make a difference, and everything fails or runs in one build (less modular, but I think for now it would be good to take a step back and go for reproducibility first...)

**Comment by mostalive** [comment]
I started at step 2 :-). Good news, https://github.com/theasp/docker-novnc builds and runs on m1. I get a desktop with an xterm that works.

```
git clone git@github.com:theasp/docker-novnc.git
cd docker-novnc
docker build --platform linux/arm64 .
docker run -p 8080:8080 <image-id>
```

**Comment by chbndrhnns** [comment]
I found your way of doing it to give me a running noVNC instance. However, it's quite inconvenient to use shortcuts there on a mac system and I have issues with key strokes repeating randomly. Of course, I do not blame that on you, however, it limits the usability a lot.

**Comment by mostalive** [comment]
Thanks for the feedback @chbndrhnns . Usability is limited (in our case balances out with having ready to go environments ). I'm experimenting with vscodium inside novnc, shortcuts out of the box seem to work better, and the other ones can be worked around in a configuration file (had some repeating keys, but not many). Less support for refactoring unfortunately (cpp, so comparing with clion).
